version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: library-manager-mysql
    environment:
      MYSQL_DATABASE: library-manager
      MYSQL_ROOT_PASSWORD: rootroot
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-manager
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/library-manager
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootroot
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    volumes:
      - logs:/app/logs

volumes:
  mysql-data:
  logs:
